server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hivernate.dialect.H2Dialect
    # 도메인 객체 구성과 DB 스키마를 비교해 필요한 테이블이나
    # 칼럼이 없을 때 도메인 객체에 맞춰 DB 스키마를 변경함
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  jwt:
    secret: huejwtsecret
  social:
    kakao:
      client_id: c685fa98f337be32a2664c7de4a04691
      redirect: /oauth
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  url:
    base: http://localhost:8080